import os

from .const import DATASOURCE_GROUP, VISUALIZER_GROUP
from graph.use_cases.search_service import SearchService
from graph.use_cases.filter_service import FilterService
from .executor import GraphCLI
from .plugin_recognition import PluginService

TEMPLATES_DIR = os.path.join(os.path.dirname(__file__), "../../../simple_visualizer/templates")
TEMPLATES_DIR = os.path.abspath(TEMPLATES_DIR)

class MainView(object):
    """Main entry point for rendering graphs with datasource and visualizer plugins.

    The `MainView` class coordinates the following steps:
    - Loads a graph from a datasource plugin.
    - Applies search and filter operations if present in the workspace.
    - Executes optional CLI commands on the graph.
    - Renders the graph using a selected visualizer plugin.

    Attributes:
        __plugin_service (PluginService): Service responsible for managing plugins.
    """

    def __init__(self, plugin_service: PluginService):
        """Initializes the `MainView`.

        Args:
            plugin_service (PluginService): The service that provides access
                to registered datasource and visualizer plugins.
        """
        self.__plugin_service = plugin_service

    def render(self, datasource_id: str, visualizer_id: str, **kwargs) -> (str, str):
        """Renders a graph visualization based on the selected datasource and visualizer.

        Workflow:
            1. Retrieves the appropriate datasource plugin by `datasource_id`.
            2. Loads the graph using the datasource plugin.
            3. Applies workspace operations:
                - Searches (via `SearchService`).
                - Filters (via `FilterService`).
                - CLI commands (via `GraphCLI`).
            4. Passes the graph to the selected visualizer plugin to produce output.

        Args:
            datasource_id (str): Identifier of the datasource plugin to use.
            visualizer_id (str): Identifier of the visualizer plugin to use.
            **kwargs: Additional keyword arguments, including:
                - `request`: Optional HTTP request object, used to retrieve
                  workspace data from session.
                - `workspace`: Optional dictionary containing:
                    - `searches`: list[str] of search queries.
                    - `filters`: list[dict] of filter conditions.
                    - `cli_commands`: list[str] of CLI commands to run.

        Returns:
            tuple[str, str]: A tuple containing:
                - HTML content generated by the visualizer plugin.
                - Any additional string output (e.g., script or metadata).

        Example:
            >>> mv = MainView(plugin_service)
            >>> html, extra = mv.render(
            ...     datasource_id="datasource_json",
            ...     visualizer_id="visualizer_simple",
            ...     file_path="people.json",
            ...     workspace={"searches": ["Alice"]}
            ... )
            >>> "<svg" in html
            True
        """
        if not datasource_id or not visualizer_id:
            return "", ""

        request = kwargs.get("request")
        workspace = kwargs.get("workspace")

        if not workspace and request:
            workspace_id = request.GET.get("workspace_id", "default")
            all_workspaces = request.session.get("workspaces", {})
            workspace = all_workspaces.get(workspace_id, {"searches": [], "filters": []})

        datasource_plugins = self.__plugin_service.plugins.get(DATASOURCE_GROUP, [])
        graph = None

        for plugin in datasource_plugins:
            if plugin.identifier() == datasource_id:
                try:
                    clean_kwargs = {k: v for k, v in kwargs.items() if v is not None}
                    graph = plugin.load(**clean_kwargs)

                    if workspace:
                        searches = workspace.get("searches", [])
                        if searches:
                            graph = SearchService.search(graph, searches)

                        filters = workspace.get("filters", [])
                        if filters:
                            graph = FilterService.apply_filters(graph, filters)

                        cli_commands = workspace.get("cli_commands", [])
                        if cli_commands:
                            cli = GraphCLI(graph)
                            for cmd in cli_commands:
                                cli.run(cmd)
                            graph = cli.graph

                except Exception as e:
                    print("Datasource plugin error:", e)
                    return "<h3>Error loading graph</h3>", ""
                break

        if not graph:
            return "<h3>No graph data available</h3>", ""

        visualizer_plugins = self.__plugin_service.plugins.get(VISUALIZER_GROUP, [])
        visualizer = next((p for p in visualizer_plugins if p.identifier() == visualizer_id), None)

        if not visualizer:
            return "<h3>No visualizer available</h3>", ""

        return visualizer.visualize(graph)
