[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "platform"
version = "0.1"
description = "Core platform for the project."
dependencies = [
    "graph-api==0.1",
    "jinja2==3.1.4"
]

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.data-files]
templates = ["templates/*"]

[tool.setuptools]
provides = ["platform"]
