[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "data_source_plugin_xml"
version = "0.1"
description = "Data source plugin for loading graphs from XML files."
dependencies = [
    "graph-api==0.1"
]

[project.entry-points."graph.datasource"]
xml_datasource = "graph.xml_datasource.xml_datasource_plugin:XMLDataSourcePlugin"

[tool.setuptools.packages.find]
where = ["."]
include = ["graph*"]

[tool.setuptools]
provides = ["data_source_plugin_xml"]
