[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-visualizer-simple"
version = "0.1"
description = "Simple visualizer plugin for graph rendering."
dependencies = [
    "graph-api==0.1",
    "Jinja2>=3.0",
    "Django>=5.1"
]

[project.entry-points."graph.visualizer"]
visualizer_simple = "graph.simple.plugin:SimpleVisualizer"

[tool.setuptools]
provides = ["plugin"]
